architect:
  - amihaiemil
env:
  MAVEN_OPTS: "-XX:MaxPermSize=256m -Xmx1g"
merge:
  script: |-
    mvn clean install
release:
  script: |-
    chmod +x ./rrv.sh
    ./rrv.sh
deploy:
  script:
   - echo "Deployment to AWS EC2 tbd in the future..."
