architect:
  - amihaiemil
env:
  MAVEN_OPTS: "-XX:MaxPermSize=256m -Xmx1g"
merge:
  script: |-
    cd charles-github-notifications-ejb
    mvn clean install
    cd ../charles-rest
    mvn clean install
deploy:
  script:
   - echo "Deployment to AWS EC2 tbd in the future..."
